# RamsonwareSense
## Notebook 1: Data Understanding and Cleaning

### Project Overview

This project aims to develop machine learning models capable of predicting the impact of ransomware attacks using historical cybersecurity incident data.

The objectives of this notebook are to:

- Load the ransomware dataset
- Explore its structure
- Identify missing values and duplicates
- Understand each feature
- Convert data into appropriate formats
- Prepare a clean dataset for exploratory data analysis (EDA)

This notebook represents the first stage of the CRISP-DM data science methodology: **Business Understanding and Data Understanding**.

In [1]:
# Import required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display all columns
pd.set_option('display.max_columns', None)

# Improve notebook appearance
plt.style.use('ggplot')

# Loading the Dataset

The ransomware attack dataset is loaded into a pandas DataFrame for analysis.

The first few rows are displayed to obtain an initial understanding of the data structure and feature values.

In [ ]:
df = pd.read_excel("../data/raw/realistic_ransomware_attacks_dataset.xlsx")

df.head()

,Attack_ID,Company_Name,Industry,Country,Attack_Date,Ransomware_Group,Attack_Vector,Ransom_Amount_USD,Payment_Status,Data_Exfiltration,Downtime_Days,Records_Affected,Estimated_Total_Loss_USD,Severity_Score
0,RA-100000,Mcdonald-Smith,Government,United Kingdom,2024-08-02,BlackCat,Drive-by Download,938912,Paid,No,2,2307213,1462487,3.55
1,RA-100001,Lopez and Sons,Transportation,Japan,2021-03-07,LockBit,Credential Theft,254957,Not Paid,No,6,1834168,752882,2.99
2,RA-100002,Anthony Group,Healthcare,United Kingdom,2022-03-28,Ryuk,Malicious Attachment,3773238,Negotiated,Yes,38,2333732,5480736,11.81
3,RA-100003,"Rodriguez, Romero and Mills",Finance,Australia,2022-03-17,Maze,Credential Theft,2828559,Negotiated,Yes,7,778108,3635324,4.66
4,RA-100004,Brown LLC,Technology,South Africa,2025-02-03,Hive,Malicious Attachment,3858935,Negotiated,Yes,35,1047217,5803128,10.16

# Dataset Dimensions

Understanding the size of the dataset helps determine the scale of the analysis.

The dataset dimensions indicate:

- Number of observations (rows)
- Number of variables (columns)

In [3]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.shape

Rows: 5000
Columns: 14

(5000, 14)

# Dataset Information

The `.info()` function provides:

- Data types
- Number of non-null values
- Memory usage

This helps identify incorrect data types and potential missing values.

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Attack_ID                 5000 non-null   str
 1   Company_Name              5000 non-null   str
 2   Industry                  5000 non-null   str
 3   Country                   5000 non-null   str
 4   Attack_Date               5000 non-null   str
 5   Ransomware_Group          5000 non-null   str
 6   Attack_Vector             5000 non-null   str
 7   Ransom_Amount_USD         5000 non-null   int64
 8   Payment_Status            5000 non-null   str
 9   Data_Exfiltration         5000 non-null   str
 10  Downtime_Days             5000 non-null   int64
 11  Records_Affected          5000 non-null   int64
 12  Estimated_Total_Loss_USD  5000 non-null   int64
 13  Severity_Score            5000 non-null   float64
dtypes: float64(1), int64(4), str(9)
memory usage: 958.6 KB

# Statistical Summary

Descriptive statistics provide insight into the numerical features, including:

- Mean
- Standard deviation
- Minimum
- Maximum
- Quartiles

These statistics help identify unusual values and possible outliers.

In [5]:
df.describe()

,Ransom_Amount_USD,Downtime_Days,Records_Affected,Estimated_Total_Loss_USD,Severity_Score
count,5.000000e+03,5000.000000,5.000000e+03,5.000000e+03,5000.000000
mean,2.522979e+06,30.244000,2.485618e+06,3.526212e+06,9.545264
std,1.440345e+06,17.402213,1.450526e+06,1.553324e+06,3.337204
min,5.717000e+03,1.000000,6.020000e+02,5.751200e+04,0.880000
25%,1.287672e+06,15.000000,1.230862e+06,2.291936e+06,7.020000
50%,2.512567e+06,30.000000,2.473088e+06,3.508614e+06,9.580000
75%,3.774430e+06,46.000000,3.734061e+06,4.781601e+06,11.992500
max,4.998740e+06,60.000000,4.996165e+06,6.958310e+06,18.640000

# Summary of Categorical Features

Categorical variables describe characteristics such as:

- Industry
- Country
- Attack Vector
- Payment Status
- Data Exfiltration

These variables will later require encoding before training machine learning models.

In [6]:
df.describe(include='object')

C:\Users\hlaku\AppData\Local\Temp\ipykernel_11352\87514550.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include='object')

,Attack_ID,Company_Name,Industry,Country,Attack_Date,Ransomware_Group,Attack_Vector,Payment_Status,Data_Exfiltration
count,5000,5000,5000,5000,5000,5000,5000,5000,5000
unique,5000,4562,10,10,1758,10,6,4,2
top,RA-100000,Smith and Sons,Technology,India,2022-03-28,LockBit,Phishing Email,Unknown,No
freq,1,9,531,544,8,521,844,1342,2501

# Checking for Missing Values

Missing values can reduce model performance and may require imputation.

This section calculates the number and percentage of missing values in each feature.

In [7]:
missing = df.isnull().sum()

missing_percentage = (missing / len(df)) * 100

missing_table = pd.DataFrame({
    "Missing Values": missing,
    "Percentage": missing_percentage
})

missing_table

                          Missing Values  Percentage
Attack_ID                              0         0.0
Company_Name                           0         0.0
Industry                               0         0.0
Country                                0         0.0
Attack_Date                            0         0.0
Ransomware_Group                       0         0.0
Attack_Vector                          0         0.0
Ransom_Amount_USD                      0         0.0
Payment_Status                         0         0.0
Data_Exfiltration                      0         0.0
Downtime_Days                          0         0.0
Records_Affected                       0         0.0
Estimated_Total_Loss_USD               0         0.0
Severity_Score                         0         0.0

# Checking for Duplicate Records

Duplicate observations may bias machine learning models.

This section identifies duplicate rows within the dataset.

In [8]:
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

In [9]:
# Remove duplicates if they exist

df = df.drop_duplicates()

print("New Shape:", df.shape)

New Shape: (5000, 14)

# Column Names

Reviewing the feature names helps us understand the information available for prediction.

These variables will later be categorized as:

- Numerical Features
- Categorical Features
- Target Variables

In [10]:
df.columns

Index(['Attack_ID', 'Company_Name', 'Industry', 'Country', 'Attack_Date',
       'Ransomware_Group', 'Attack_Vector', 'Ransom_Amount_USD',
       'Payment_Status', 'Data_Exfiltration', 'Downtime_Days',
       'Records_Affected', 'Estimated_Total_Loss_USD', 'Severity_Score'],
      dtype='str')

# Understanding Categorical Variables

Machine learning algorithms require numerical input.

Before encoding categorical variables, it is important to inspect their unique values and identify inconsistencies such as:

- Different spellings
- Capitalization differences
- Unexpected categories

In [11]:
categorical_columns = [
    "Industry",
    "Country",
    "Ransomware_Group",
    "Attack_Vector",
    "Payment_Status",
    "Data_Exfiltration"
]

for column in categorical_columns:
    print("=" * 50)
    print(column)
    print(df[column].unique())

==================================================
Industry
<ArrowStringArray>
[    'Government', 'Transportation',     'Healthcare',        'Finance',
     'Technology',         'Retail',         'Energy',  'Manufacturing',
    'Hospitality',      'Education']
Length: 10, dtype: str
==================================================
Country
<ArrowStringArray>
['United Kingdom',          'Japan',      'Australia',   'South Africa',
         'Canada',        'Germany',         'France',  'United States',
         'Brazil',          'India']
Length: 10, dtype: str
==================================================
Ransomware_Group
<ArrowStringArray>
['BlackCat',  'LockBit',     'Ryuk',     'Maze',     'Hive',    'Conti',
    'REvil',     'Clop',    'Akira', 'DarkSide']
Length: 10, dtype: str
==================================================
Attack_Vector
<ArrowStringArray>
[   'Drive-by Download',     'Credential Theft', 'Malicious Attachment',
       'Phishing Email',          'RDP Exploit',     'Zero-Day Exploit']
Length: 6, dtype: str
==================================================
Payment_Status
<ArrowStringArray>
['Paid', 'Not Paid', 'Negotiated', 'Unknown']
Length: 4, dtype: str
==================================================
Data_Exfiltration
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

# Frequency Distribution of Categories

The frequency of each category provides insight into the distribution of ransomware attacks across industries, countries, and attack vectors.

This information will later be visualized during exploratory data analysis.

In [12]:
for column in categorical_columns:
    print("\n")
    print("=" * 50)
    print(column)
    print(df[column].value_counts())

==================================================
Industry
Industry
Technology        531
Transportation    518
Healthcare        517
Retail            507
Manufacturing     507
Hospitality       496
Education         485
Finance           483
Government        479
Energy            477
Name: count, dtype: int64


==================================================
Country
Country
India             544
Brazil            530
United Kingdom    516
United States     511
Australia         509
Canada            505
South Africa      496
Germany           472
Japan             462
France            455
Name: count, dtype: int64


==================================================
Ransomware_Group
Ransomware_Group
LockBit     521
Clop        517
Akira       517
Ryuk        515
Conti       505
DarkSide    494
BlackCat    489
Hive        482
REvil       482
Maze        478
Name: count, dtype: int64


==================================================
Attack_Vector
Attack_Vector
Phishing Email          844
Zero-Day Exploit        834
Malicious Attachment    833
Drive-by Download       832
RDP Exploit             832
Credential Theft        825
Name: count, dtype: int64


==================================================
Payment_Status
Payment_Status
Unknown       1342
Not Paid      1228
Negotiated    1222
Paid          1208
Name: count, dtype: int64


==================================================
Data_Exfiltration
Data_Exfiltration
No     2501
Yes    2499
Name: count, dtype: int64

# Converting Date Features

The `Attack_Date` column is converted into the datetime format to enable time-based analysis.

This will allow future exploration of:

- Monthly attack trends
- Annual attack trends
- Seasonal patterns

In [13]:
df["Attack_Date"] = pd.to_datetime(df["Attack_Date"])

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Attack_ID                 5000 non-null   str
 1   Company_Name              5000 non-null   str
 2   Industry                  5000 non-null   str
 3   Country                   5000 non-null   str
 4   Attack_Date               5000 non-null   datetime64[us]
 5   Ransomware_Group          5000 non-null   str
 6   Attack_Vector             5000 non-null   str
 7   Ransom_Amount_USD         5000 non-null   int64
 8   Payment_Status            5000 non-null   str
 9   Data_Exfiltration         5000 non-null   str
 10  Downtime_Days             5000 non-null   int64
 11  Records_Affected          5000 non-null   int64
 12  Estimated_Total_Loss_USD  5000 non-null   int64
 13  Severity_Score            5000 non-null   float64
dtypes: datetime64[us](1), float64(1), int64(4), str(8)
memory usage: 909.8 KB

# Data Types After Conversion

The dataset is inspected once more to verify that the date conversion was successful.

In [14]:
df.dtypes

Attack_ID                              str
Company_Name                           str
Industry                               str
Country                                str
Attack_Date                 datetime64[us]
Ransomware_Group                       str
Attack_Vector                          str
Ransom_Amount_USD                    int64
Payment_Status                         str
Data_Exfiltration                      str
Downtime_Days                        int64
Records_Affected                     int64
Estimated_Total_Loss_USD             int64
Severity_Score                     float64
dtype: object

# Numerical and Categorical Features

Separating feature types simplifies preprocessing during model development.

In [15]:
numerical_columns = df.select_dtypes(include=['int64','float64']).columns

categorical_columns = df.select_dtypes(include=['object']).columns

print("Numerical Features")
print(numerical_columns)

print("\nCategorical Features")
print(categorical_columns)

Numerical Features
Index(['Ransom_Amount_USD', 'Downtime_Days', 'Records_Affected',
       'Estimated_Total_Loss_USD', 'Severity_Score'],
      dtype='str')

Categorical Features
Index(['Attack_ID', 'Company_Name', 'Industry', 'Country', 'Ransomware_Group',
       'Attack_Vector', 'Payment_Status', 'Data_Exfiltration'],
      dtype='str')

C:\Users\hlaku\AppData\Local\Temp\ipykernel_11352\2185792097.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include=['object']).columns

# Saving the Clean Dataset

After completing the initial inspection, the cleaned dataset is saved for use in subsequent notebooks.

Future notebooks will use this dataset instead of the raw data.

In [ ]:
df.to_csv("../data/processed/cleaned_ransomware_dataset.csv", index=False)

print("Dataset saved successfully.")

Dataset saved successfully.

# Conclusion

The dataset has been successfully loaded and inspected.

The following tasks were completed:

- Loaded the ransomware dataset
- Examined dataset dimensions
- Reviewed data types
- Generated descriptive statistics
- Checked for missing values
- Checked for duplicate records
- Examined categorical variables
- Converted the attack date into datetime format
- Identified numerical and categorical features
- Saved a cleaned version of the dataset

The dataset is now ready for **Exploratory Data Analysis (EDA)**, where relationships between variables, trends, and patterns will be investigated before machine learning models are developed.